/* Código Creado por Jose XrL
Free codes Titans 
https://whatsapp.com/channel/0029ValMlRS6buMFL9d0iQ0S
*/

import moment from 'moment-timezone';

const handler = async (m, { conn }) => {
    let who = m.mentionedJid && m.mentionedJid[0] ? m.mentionedJid[0] : m.fromMe ? conn.user.jid : m.sender;
    let pp = await conn.profilePictureUrl(who, 'image').catch(_ => 'https://qu.ax/GJtrr.jpg'); 
    let username = conn.getName(who);

    let now = new Date();
    let date = now.toLocaleDateString('es-ES', { year: 'numeric', month: 'long', day: 'numeric' });
    let time = now.toLocaleTimeString('es-ES', { hour: '2-digit', minute: '2-digit', second: '2-digit' });

    const timeZones = {
        'Afganistán': 'Asia/Kabul',
        'Albania': 'Europe/Tirana',
        'Alemania': 'Europe/Berlin',
        'Andorra': 'Europe/Andorra',
        'Angola': 'Africa/Luanda',
        'Antigua y Barbuda': 'America/Antigua',
        'Arabia Saudita': 'Asia/Riyadh',
        'Argelia': 'Africa/Algiers',
        'Argentina': 'America/Argentina/Buenos_Aires',
        'Armenia': 'Asia/Yerevan',
        'Australia': 'Australia/Sydney',
        'Austria': 'Europe/Vienna',
        'Azerbaiyán': 'Asia/Baku',
        'Bahamas': 'America/Nassau',
        'Bahréin': 'Asia/Bahrain',
        'Bangladesh': 'Asia/Dhaka',
        'Barbados': 'America/Barbados',
        'Bélgica': 'Europe/Brussels',
        'Belice': 'America/Belize',
        'Benín': 'Africa/Porto-Novo',
        'Bielorrusia': 'Europe/Minsk',
        'Bolivia': 'America/La_Paz',
        'Bosnia y Herzegovina': 'Europe/Sarajevo',
        'Botsuana': 'Africa/Gaborone',
        'Brasil': 'America/Sao_Paulo',
        'Brunéi': 'Asia/Brunei',
        'Burkina Faso': 'Africa/Ouagadougou',
        'Burundi': 'Africa/Bujumbura',
        'Cabo Verde': 'Atlantic/Cape_Verde',
        'Camerún': 'Africa/Douala',
        'Canadá': 'America/Toronto',
        'República Centroafricana': 'Africa/Bangui',
        'Chad': 'Africa/Ndjamena',
        'Chile': 'America/Santiago',
        'China': 'Asia/Shanghai',
        'Colombia': 'America/Bogota',
        'Comoras': 'Indian/Comoro',
        'Congo (República del)': 'Africa/Brazzaville',
        'Congo (República Democrática del)': 'Africa/Kinshasa',
        'Costa Rica': 'America/Costa_Rica',
        'Croacia': 'Europe/Zagreb',
        'Cuba': 'America/Havana',
        'Dinamarca': 'Europe/Copenhagen',
        'Dominica': 'America/Dominica',
        'Dominicana (República)': 'America/Santo_Domingo',
        'Ecuador': 'America/Guayaquil',
        'Egipto': 'Africa/Cairo',
        'El Salvador': 'America/El_Salvador',
        'Emiratos Árabes Unidos': 'Asia/Dubai',
        'Escocia': 'Europe/London',
        'España': 'Europe/Madrid',
        'Estonia': 'Europe/Tallinn',
        'Estados Unidos': 'America/New_York',
        'Etiopía': 'Africa/Addis_Ababa',
        'Fiji': 'Pacific/Fiji',
        'Filipinas': 'Asia/Manila',
        'Finlandia': 'Europe/Helsinki',
        'Francia': 'Europe/Paris',
        'Gambia': 'Africa/Banjul',
        'Georgia': 'Asia/Tbilisi',
        'Ghana': 'Africa/Accra',
        'Grecia': 'Europe/Athens',
        'Grenada': 'America/Grenada',
        'Guatemala': 'America/Guatemala',
        'Guinea': 'Africa/Conakry',
        'Guinea Ecuatorial': 'Africa/Malabo',
        'Guyana': 'America/Guyana',
        'Haití': 'America/Port-au-Prince',
        'Holanda': 'Europe/Amsterdam',
        'Honduras': 'America/Tegucigalpa',
        'Hungría': 'Europe/Budapest',
        'India': 'Asia/Kolkata',
        'Indonesia': 'Asia/Jakarta',
        'Irak': 'Asia/Baghdad',
        'Irán': 'Asia/Tehran',
        'Irlanda': 'Europe/Dublin',
        'Islandia': 'Atlantic/Reykjavik',
        'Islas Marshall': 'Pacific/Majuro',
        'Islas Salomón': 'Pacific/Guadalcanal',
        'Italia': 'Europe/Rome',
        'Jamaica': 'America/Jamaica',
        'Japón': 'Asia/Tokyo',
        'Jordania': 'Asia/Amman',
        'Kazajistán': 'Asia/Almaty',
        'Kenia': 'Africa/Nairobi',
        'Kirguistán': 'Asia/Bishkek',
        'Kiribati': 'Pacific/Tarawa',
        'Kuwait': 'Asia/Kuwait',
        'Laos': 'Asia/Vientiane',
        'Lesoto': 'Africa/Maseru',
        'Letonia': 'Europe/Riga',
        'Líbano': 'Asia/Beirut',
        'Liberia': 'Africa/Monrovia',
        'Libia': 'Africa/Tripoli',
        'Lituania': 'Europe/Vilnius',
        'Luxemburgo': 'Europe/Luxembourg',
        'Malasia': 'Asia/Kuala_Lumpur',
        'Malawi': 'Africa/Blantyre',
        'Maldivas': 'Asia/Male',
        'Malta': 'Europe/Malta',
        'Mali': 'Africa/Bamako',
        'Mauricio': 'Indian/Mauritius',
        'México': 'America/Mexico_City',
        'Mónaco': 'Europe/Monaco',
        'Mongolia': 'Asia/Ulaanbaatar',
        'Montenegro': 'Europe/Belgrade',
        'Mozambique': 'Africa/Maputo',
        'Namibia': 'Africa/Windhoek',
        'Nauru': 'Pacific/Nauru',
        'Nepal': 'Asia/Kathmandu',
        'Nicaragua': 'America/Managua',
        'Níger': 'Africa/Niamey',
        'Nigeria': 'Africa/Lagos',
        'Noruega': 'Europe/Oslo',
        'Nueva Zelanda': 'Pacific/Auckland',
        'Omán': 'Asia/Muscat',
        'Pakistán': 'Asia/Karachi',
        'Palaos': 'Pacific/Palau',
        'Panamá': 'America/Panama',
        'Papúa Nueva Guinea': 'Pacific/Port_Moresby',
        'Paraguay': 'America/Asuncion',
        'Perú': 'America/Lima',
        'Filipinas': 'Asia/Manila',
        'República Dominicana': 'America/Santo_Domingo',
        'Ruanda': 'Africa/Kigali',
        'Rumanía': 'Europe/Bucharest',
        'Rusia': 'Europe/Moscow',
        'Samoa': 'Pacific/Apia',
        'San Cristóbal y Nieves': 'America/St_Kitts',
        'San Marino': 'Europe/San_Marino',
        'Santa Lucía': 'America/St_Lucia',
        'Santo Tomé y Príncipe': 'Africa/Sao_Tome',
        'Senegal': 'Africa/Dakar',
        'Serbia': 'Europe/Belgrade',
        'Seychelles': 'Indian/Sciences',
        'Singapur': 'Asia/Singapore',
        'Siria': 'Asia/Damascus',
        'Sudáfrica': 'Africa/Johannesburg',
        'Sudán': 'Africa/Khartoum',
        'Suecia': 'Europe/Stockholm',
        'Suiza': 'Europe/Zurich',
        'Tailandia': 'Asia/Bangkok',
        'Timor Oriental': 'Asia/Dili',
        'Tonga': 'Pacific/Tongatapu',
        'Túnez': 'Africa/Tunis',
        'Turkmenistán': 'Asia/Ashgabat',
        'Turquía': 'Europe/Istanbul',
        'Tuvalu': 'Pacific/Funafuti',
        'Uganda': 'Africa/Kampala',
        'Ucrania': 'Europe/Kiev',
        'Uruguay': 'America/Montevideo',
        'Uzbekistán': 'Asia/Tashkent',
        'Vanuatu': 'Pacific/Efate',
        'Vaticano': 'Europe/Vatican',
        'Venezuela': 'America/Caracas',
        'Vietnam': 'Asia/Ho_Chi_Minh',
        'Yemen': 'Asia/Aden',
        'Zambia': 'Africa/Lusaka',
        'Zimbabue': 'Africa/Harare',
    };

    let timeMessage = '*`—  H O R A S  D E  P A Í S E S`*\n\n';
    for (const [country, tz] of Object.entries(timeZones)) {
        const countryTime = moment().tz(tz).format('DD/MM HH:mm');
        timeMessage += `⏱️ *${country}*: ${countryTime}\n`;
    }

    timeMessage += `\n*» Fecha del servidor* :: ${date}\n`;
    timeMessage += `*» Hora del servidor* :: ${time}\n\n`;
    timeMessage += `> Escribe *!horario* para ver esta información nuevamente.`;

    conn.sendFile(m.chat, pp, 'perfil.jpg', timeMessage, m, false, { mentions: [who] });
};

handler.help = ['horario'];
handler.tags = ['info'];
handler.command = ['horario']

export default handler;